name: github pages

on:
  repository_dispatch:
    types: [update_works]
  push:
    tags:
      - 'v*'
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: search flutter cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
      - name: Install
        run: flutter pub get
      - name: Fetch blog data
        run: flutter pub run static_data_fetcher
      - name: Create .env file
        env:
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}
        run: echo API_KEY=$MICRO_CMS_API_KEY > .env
      - name: Fetch api data
        run: flutter pub run static_micro_cms
      - name: Build
        run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FASTRIVER_DEV_MICRO }}'
          projectId: fastriver-dev-micro
          channelId: live
