name: github pages

on:
  repository_dispatch:
    types: [update_works]
  push:
    tags:
      - 'v*'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
      - name: Install
        run: flutter pub get
      - name: Create .env file
        env:
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}
        run: echo API_KEY=$MICRO_CMS_API_KEY > .env
      - name: Fetch api data
        run: flutter pub run generator
      - name: Build
        run: flutter build web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.8.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./example/build/web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FASTRIVER_DEV_MICRO }}'
          projectId: fastriver-dev-micro